site_name: Projectopia
repo_url: https://github.com/projectopia/docs
repo_name: projectopia/docs
theme:
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.indexes
    - navigation.tracking
    - announce.dismiss
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences